Repository contactsimonwilson/PubRemote, pull requests merged in 2025-05, with the labels that each got.

#213 Send build guides to quick start at the end
  docs/builds/leaf-blaster.md
  docs/builds/snowmote.md
Labels: documentation

#214 Add HUD mode
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/PubRemote_events.py
  firmware/src/remote/settings.c
  firmware/src/remote/settings.h
  firmware/src/remote/transmitter.c
  firmware/src/screens/menu_screen.c
  firmware/src/screens/stats_screen.c
  firmware/src/ui/ui.c
  firmware/src/ui/ui.h
  firmware/src/ui/ui_MenuScreen.c
  firmware/src/ui/ui_StatsScreen.c
  firmware/src/ui/ui_events.h
  prebuild_hook.py
Labels: enhancement

#218 Add a favicon 2.0
  firmware_tool/index.html
  firmware_tool/public/favicon.ico
  firmware_tool/public/favicon.svg
Labels: enhancement, nice-to-have

#221 Add Remote Mode label field
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/src/screens/stats_screen.c
  firmware/src/ui/ui.c
  firmware/src/ui/ui.h
  firmware/src/ui/ui_StatsScreen.c
  prebuild_hook.py
Labels: enhancement
