Repository contactsimonwilson/PubRemote, pull requests merged in 2025-02, with the labels that each got.

#126 Add RSSI/DC readout/Temps/Trip Distance
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/src/colors.h
  firmware/src/remote/connection.c
  firmware/src/remote/espnow.c
  firmware/src/remote/receiver.c
  firmware/src/remote/receiver.h
  firmware/src/remote/stats.c
  firmware/src/remote/stats.h
  firmware/src/screens/stats_screen.c
  firmware/src/screens/stats_screen.h
  firmware/src/ui/ui.c
  firmware/src/ui/ui.h
  firmware/src/ui/ui_StatsScreen.c
  firmware/src/utilities/conversion_utils.h
  prebuild_hook.py
Labels: enhancement

#129 Fix stats_screen.c typo, RSSI show/hide, Add degree symbol
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/src/remote/connection.c
  firmware/src/remote/stats.c
  firmware/src/screens/stats_screen.c
  firmware/src/screens/stats_screen.h
  firmware/src/ui/ui_StatsScreen.c
Labels: enhancement

#130 Add check for connection state
  firmware/src/screens/stats_screen.c
Labels: bugfix

#131 Bump version to v0.0.8
  prebuild_hook.py
Labels: maintenance

#134 Add Float Accessories preview package, Update web tool
  firmware_tool/public/float_accessories/float_accessories-2.5-preview-3.vescpkg.zip
  firmware_tool/src/App.tsx
  firmware_tool/src/components/FloatAccessoriesSelector.tsx
Labels: documentation, maintenance

#139 Fix dark text toggle crash
  firmware/src/utilities/screen_utils.c
Labels: bugfix

#140 Fix Calibration Invert Y
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/PubRemote_events.py
  firmware/src/remote/remoteinputs.c
  firmware/src/remote/settings.c
  firmware/src/screens/calibration_screen.c
  firmware/src/ui/ui.c
  firmware/src/ui/ui.h
  firmware/src/ui/ui_CalibrationScreen.c
  prebuild_hook.py
Labels: bugfix, v0.1-needs

#142 Nightly Builds + About screen updates
  .github/workflows/nightly-build.yml
  .github/workflows/release.yml
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/src/screens/about_screen.c
  firmware/src/screens/calibration_screen.c
  firmware/src/ui/ui.c
  firmware/src/ui/ui.h
  firmware/src/ui/ui_AboutScreen.c
  firmware/src/ui/ui_BMSScreen.c
  firmware/src/ui/ui_CalibrationScreen.c
  firmware/src/ui/ui_PairingScreen.c
  firmware/src/ui/ui_SettingsScreen.c
  firmware/src/utilities/string_utils.c
  firmware/src/utilities/string_utils.h
  postbuild_hook.py
  prebuild_hook.py
Labels: enhancement

#148 Add version string to ZIP files on release
  .github/workflows/nightly-build.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  firmware_tool/src/hooks/useFirmware.ts
  postbuild_hook.py
  prebuild_hook.py
Labels: maintenance

#145 UI Text updates
  firmware/PubRemote.sll
  firmware/PubRemote.spj
  firmware/src/ui/ui_AboutScreen.c
  firmware/src/ui/ui_BMSScreen.c
  firmware/src/ui/ui_PairingScreen.c
Labels: maintenance

#152 Update float accessories package install steps
  firmware_tool/src/components/FloatAccessoriesSelector.tsx
Labels: documentation

#157 Add automated release tagging and push on update of prebuild_hook.py
  .github/workflows/release.yml
  prebuild_hook.py
Labels: enhancement, maintenance

#160 Add waveshare_esp32s3_touch_amoled_143 to default build list
  platformio.ini
Labels: maintenance
